### ISSUE TITLE
Location of config file and path to lint are the same causing pathing issue

### ISSUE THREAD

**Issue by brandtdaniels** [dmiluski/bitrise-step-swiftformat#2]
BITRISE_PROJECT_DIR=CRM

my config file is: $BITRISE_PROJECT_DIR/.swiftformat and my path to lint is $BITRISE_PROJECT_DIR

This caused the error 

error: Specified config file does not exist: /Users/vagrant/git/**CRM/CRM**/.swiftformat.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | swiftformat@0 (exit code: 70)                                 | 7.50 sec |

**Comment by dmiluski** [comment]
Hi @brandtdaniels , 

Is there any chance you have a publicly available project to see which is running this step? By default, as long as the `.swiftformat` file is in the root of the repo it works as expected. 

If I had a reproducing repro, it would be very helpful to debug.

**Comment by brandtdaniels** [comment]
I do not...what ended up working for me is setting the path where swiftformat should lint to be $BITRISE_PROJECT_PATH and leaving the Format configuration file setting blank.

Maybe you should default the required field `Select the path where SwiftFormat should lint` to $BITRISE_SOURCE_DIR for most. As it's most likely that is where their .swiftformat will be.

**Comment by dmiluski** [comment]
Default uses the paths to the BITRISE_SOURCE_DIR as well as .swiftformat file, similar to SwiftLint.

![Screen Shot 2020-10-30 at 8 31 31 AM](https://user-images.githubusercontent.com/5083390/97724601-5a6f8880-1a8a-11eb-90fd-3d6738fc45c4.png)

eg.
![Screen Shot 2020-10-30 at 8 33 55 AM](https://user-images.githubusercontent.com/5083390/97725237-2c3e7880-1a8b-11eb-8216-8658a5bff073.png)

That being said, if you want to place it somewhere else, you can. The input variables (path/config) just need to reference those paths to execute properly.
