### ISSUE TITLE
Does this use Brewfile

### ISSUE THREAD

**Issue by brandtdaniels** [dmiluski/bitrise-step-swiftformat#4]
I have a Brewfile that lists swiftformat. Does this step work with that? I want to ensure the same version of swiftformat is used throught the team.

**Comment by dmiluski** [comment]
Hi @brandtdaniels ,

Bitrise steps specify dependencies via a step yaml file, outside of a project brew file.

This step was modeled after [Bitrise Step Swiftlint](https://github.com/kimdv/bitrise-step-swiftlint) which runs the tool as a linter to confirm a PR or CI job conforms to the required format rules.

Bitrise steps include their own dependency requirements defined in the step yaml:
https://github.com/kimdv/bitrise-step-swiftlint

```
deps:
  brew:
  - name: swiftlint
```

So you should not need to install something other than the step to run an extra step other than including this step in your workflow.

Something to be aware of, that may not be related to your question.
One quirk that happened over the past few days was that the Xcode 12.1 stack experiences brew install failures the past few days. Which was resolved just a day or two ago that was causing some mishaps with installing the latest swiftformat which plays friendly with Xcode 12.1 guard indenting styles.

**Comment by brandtdaniels** [comment]
Thank you
